### ISSUE TITLE
Project part 2 issues (font icon)

### ISSUE THREAD

**Issue by kresnasatya** [udacity/responsive-images#12]
Hi team, thanks for providing this good course for me. It's a good thing that web developer should care about images, typography when develop website. When I'm using [fontawesome](http://fontawesome.io/) to get facebook, twitter, google+, and digg, the Udacity feedback extension doesn't respons it (I have refresh it several times in Google Chrome browser). This is the screenshot:

![responsive images feedback course](https://cloud.githubusercontent.com/assets/11099186/18504073/f232c12e-7a92-11e6-89c6-f5600181f670.png)

This is the [Gist Code](https://gist.github.com/satyakresna/708f2c15b5d22c6ba76435385ddc49a1)

But, when I see your project-2 solution, it use the [We Love Font Icons](http://weloveiconfonts.com/) website as the provider font icon. Why only this website can recognized by Udacity feedback extension? I think it should be fix it, so that's not only We Love Font Icons but Font awesome and other font icons website can recognized by Udacity feedback extension. Thank you very much.

**Comment by samdutton** [comment]
Hi Satya! I'm just checking with Udacity — someone should get back to you
shortly.

**Comment by kresnasatya** [comment]
Ok. Thank you Mr. Samdutton.

**Comment by vickyvishal** [comment]
I am having the same issue. Although i used the http://weloveiconfonts.com/ as the provider font icon, The chrome extension is not identifying the change.

**Comment by cameronwp** [comment]
Hi everyone. Sorry for the delay here. We're looking into it now.

**Comment by kresnasatya** [comment]
Yes, please. Thank you
